const blogs = [
  {
    title: "The Future of AI in Daily Life",
    slug: "future-of-ai-daily-life",
    content: "Artificial Intelligence is rapidly evolving and is becoming part of our everyday routines. From smart assistants to personalized recommendations, AI is transforming how we interact with technology. This blog explores emerging AI trends, their applications in homes and workplaces, and ethical considerations for the future.",
    coverImage: "https://images.unsplash.com/photo-1516321310762-9d8e315a7e84?q=80&w=2000&auto=format&fit=crop",
    author: "6811dcf7d835fa34c6201ca5",
    tags: ["AI", "Technology", "Future"],
    category: "Technology",
    isPublished: true,
    readingTime: "5 min",
    views: 126,
    createdAt: new Date("2025-04-30T08:52:46.946Z"),
    updatedAt: new Date("2025-05-27T06:59:00.000Z")
  },
  {
    title: "Healthy Eating Habits for a Modern Lifestyle",
    slug: "healthy-eating-modern-lifestyle",
    content: "Eating healthy doesn't have to be complicated. This blog covers practical tips for incorporating balanced meals into busy schedules, including meal prep ideas, superfood choices, and mindful eating practices to enhance well-being.",
    coverImage: "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=2000&auto=format&fit=crop",
    author: "6811dcf7d835fa34c6201ca6",
    tags: ["Health", "Nutrition", "Lifestyle"],
    category: "Lifestyle",
    isPublished: true,
    readingTime: "4 min",
    views: 143,
    createdAt: new Date("2025-04-30T08:52:46.946Z"),
    updatedAt: new Date("2025-05-27T06:59:00.000Z")
  },
  {
    title: "Mastering JavaScript for Beginners",
    slug: "mastering-javascript-beginners",
    content: "JavaScript is one of the most essential languages for web development. This guide introduces beginners to core concepts like variables, functions, and DOM manipulation, with practical examples to build interactive web pages.",
    coverImage: "https://images.unsplash.com/photo-1526374965328-7f61d4dc18c5?q=80&w=2000&auto=format&fit=crop",
    author: "6811dcf7d835fa34c6201ca7",
    tags: ["JavaScript", "Programming", "Web Development"],
    category: "Technology",
    isPublished: false,
    readingTime: "7 min",
    views: 53,
    createdAt: new Date("2025-04-30T08:52:46.946Z"),
    updatedAt: new Date("2025-05-27T06:59:00.000Z")
  },
  {
    title: "Top 10 Travel Destinations in 2025",
    slug: "top-10-travel-2025",
    content: "From hidden gems to popular cities, here are the best places to visit in 2025. This blog highlights destinations like Iceland’s geothermal springs, Japan’s cultural hubs, and eco-friendly retreats in Costa Rica, with tips for planning your trip.",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=2000&auto=format&fit=crop",
    author: "6811dcf7d835fa34c6201ca8",
    tags: ["Travel", "Adventure", "Guide"],
    category: "Travel",
    isPublished: true,
    readingTime: "6 min",
    views: 150,
    createdAt: new Date("2025-04-30T08:52:46.946Z"),
    updatedAt: new Date("2025-05-27T06:59:00.000Z")
  },
  {
    title: "Boost Your Productivity with These Apps",
    slug: "boost-productivity-apps",
    content: "Explore the best productivity tools that can help you organize your work. From task managers like Todoist to focus apps like Forest, this blog reviews top apps to streamline your workflow and boost efficiency.",
    coverImage: "https://images.unsplash.com/photo-1516321310762-9d8e315a7e84?q=80&w=2000&auto=format&fit=crop",
    author: "6811dcf7d835fa34c6201ca9",
    tags: ["Productivity", "Apps", "Work"],
    category: "Lifestyle",
    isPublished: true,
    readingTime: "3 min",
    views: 98,
    createdAt: new Date("2025-04-30T08:52:46.946Z"),
    updatedAt: new Date("2025-05-27T06:59:00.000Z")
  },
  {
    title: "Understanding Cryptocurrency and Its Impact",
    slug: "understanding-cryptocurrency-impact",
    content: "Cryptocurrencies are reshaping the financial landscape. This blog explains how blockchain works, the rise of Bitcoin and Ethereum, and their potential to disrupt traditional banking systems.",
    coverImage: "https://images.unsplash.com/photo-1518546305927-5a555bb7020d?q=80&w=2000&auto=format&fit=crop",
    author: "6811dcf7d835fa34c6201caa",
    tags: ["Cryptocurrency", "Finance", "Blockchain"],
    category: "Finance",
    isPublished: false,
    readingTime: "8 min",
    views: 77,
    createdAt: new Date("2025-04-30T08:52:46.946Z"),
    updatedAt: new Date("2025-05-27T06:59:00.000Z")
  },
  {
    title: "Fitness Trends to Watch Out for This Year",
    slug: "fitness-trends-2025",
    content: "Stay ahead of the curve with these top fitness trends. From wearable tech to virtual workout classes, this blog explores innovative ways to stay active in 2025.",
    coverImage: "https://images.unsplash.com/photo-1517836357463-d25dfeac3438?q=80&w=2000&auto=format&fit=crop",
    author: "6811dcf7d835fa34c6201cab",
    tags: ["Fitness", "Health", "Trends"],
    category: "Lifestyle",
    isPublished: true,
    readingTime: "4 min",
    views: 110,
    createdAt: new Date("2025-04-30T08:52:46.946Z"),
    updatedAt: new Date("2025-05-27T06:59:00.000Z")
  },
  {
    title: "How to Start a Podcast from Scratch",
    slug: "start-podcast-from-scratch",
    content: "Podcasting has become a powerful medium for content creators. This step-by-step guide covers choosing a niche, selecting equipment, recording, editing, and distributing your podcast to platforms like Spotify and Apple Podcasts.",
    coverImage: "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?q=80&w=2000&auto=format&fit=crop",
    author: "6811dcf7d835fa34c6201ca5",
    tags: ["Podcast", "Media", "Content Creation"],
    category: "Lifestyle",
    isPublished: true,
    readingTime: "6 min",
    views: 102,
    createdAt: new Date("2025-04-30T08:52:46.946Z"),
    updatedAt: new Date("2025-05-27T06:59:00.000Z")
  },
  {
    title: "Learn React in 7 Days",
    slug: "learn-react-7-days",
    content: "This guide helps beginners get started with React quickly and effectively. Learn to build components, manage state, and create a simple app with hands-on tutorials and examples.",
    coverImage: "https://images.unsplash.com/photo-1633356122544-f1348ac8b547?q=80&w=2000&auto=format&fit=crop",
    author: "6811dcf7d835fa34c6201ca7",
    tags: ["React", "Frontend", "JavaScript"],
    category: "Technology",
    isPublished: true,
    readingTime: "5 min",
    views: 135,
    createdAt: new Date("2025-04-30T08:52:46.946Z"),
    updatedAt: new Date("2025-05-27T06:59:00.000Z")
  },
  {
    title: "The Art of Mindfulness: A Beginner's Guide",
    slug: "mindfulness-guide-beginners",
    content: "Mindfulness can greatly improve mental clarity and reduce stress. This beginner’s guide explains simple techniques like meditation, breathing exercises, and journaling to cultivate a mindful lifestyle.",
    coverImage: "https://images.unsplash.com/photo-1508672019048-805c876b67e2?q=80&w=2000&auto=format&fit=crop",
    author: "6811dcf7d835fa34c6201ca9",
    tags: ["Mindfulness", "Health", "Wellbeing"],
    category: "Lifestyle",
    isPublished: true,
    readingTime: "7 min",
    views: 124,
    createdAt: new Date("2025-04-30T08:52:46.946Z"),
    updatedAt: new Date("2025-05-27T06:59:00.000Z")
  },
  {
    title: "A Beginner’s Journey into Data Science",
    slug: "a-beginners-journey-into-data-science",
    content: "Introduction\nIn today's data-driven world, the ability to extract meaningful insights from raw information is more valuable than ever. Data science bridges the gap between numbers and decision-making, enabling businesses and individuals to uncover trends, solve problems, and predict outcomes.\n\nWhat is Data Science?\nData Science is an interdisciplinary field that combines statistics, computer science, and domain knowledge to analyze large volumes of data. The goal is to transform data into actionable insights using tools like Python, R, SQL, and visualization platforms like Power BI and Tableau.\n\nCore Components of Data Science:\n\nData Collection: Gathering data from multiple sources like APIs, databases, or web scraping.\n\nData Cleaning: Handling missing values, removing outliers, and formatting the data properly.\n\nExploratory Data Analysis (EDA): Using visualizations and statistics to understand the data's structure and patterns.\n\nModel Building: Applying machine learning algorithms to make predictions or classifications.\n\nData Visualization: Creating dashboards or charts to communicate findings effectively.\n\nPopular Tools & Technologies:\n\nProgramming Languages: Python, R\n\nLibraries: Pandas, NumPy, Scikit-learn, Matplotlib, Seaborn\n\nPlatforms: Power BI, Tableau, Excel\n\nWhy Choose Data Science?\nWith the explosion of digital data, every industry — from healthcare to marketing — is relying on data professionals. It’s a field with high demand, attractive salaries, and endless learning opportunities.\n\nFinal Thoughts:\nWhether you're an aspiring analyst, engineer, or researcher, learning data science equips you with a powerful skill set. Start small, stay curious, and keep practicing — the world of data is vast and full of potential.",
    coverImage: "https://www.fsm.ac.in/blog/wp-content/uploads/2022/07/FUqHEVVUsAAbZB0.jpg",
    author: "68152920f5b0da7c4cd7837c",
    tags: ["DataScience"],
    category: "Technology",
    isPublished: false,
    readingTime: "2 min",
    views: 6,
    createdAt: new Date("2025-05-02T20:28:05.965Z"),
    updatedAt: new Date("2025-05-27T06:59:00.000Z")
  },
  {
    title: "The Rise of Data Visualization in Decision Making",
    slug: "the-rise-of-data-visualization-in-decision-making",
    content: "Introduction\nIn the digital age, data alone isn't enough. What matters is how well we can interpret and present that data. Data visualization has emerged as a key skill for making informed, fast, and accurate decisions, transforming raw data into visual stories that anyone can understand.\n\nThe Power of Visualization\nHumans process visuals 60,000 times faster than text. That’s why businesses use dashboards and charts to communicate complex trends in seconds. From sales trends to customer behavior, visualizations help stakeholders grasp insights quickly and act with confidence.\n\nEvolution: From Excel to Power BI & Tableau\nEarlier, spreadsheets like Microsoft Excel were the go-to tools. But today, modern platforms like Power BI, Tableau, and Google Data Studio allow real-time data dashboards, interactive reports, and stunning visuals — all without needing deep coding knowledge.\n\nKey Benefits:\nSimplifies complex data\nEnhances decision-making\nDetects trends and outliers quickly\nEncourages data-driven culture in teams\n\nPopular Visualization Techniques:\nBar and Line Charts – Trend analysis\nHeatmaps – Highlight high/low values\nPie Charts – Composition of a whole\nScatter Plots – Relationship and distribution\nTree Maps & Sankey Diagrams – Hierarchical or flow-based data\n\nUse Cases Across Industries:\nHealthcare: Patient monitoring dashboards\nFinance: Real-time market analytics\nRetail: Customer segmentation and purchase patterns\nEducation: Student performance tracking\n\nFinal Thoughts:\nIn a world overwhelmed by data, those who can visualize it effectively hold a competitive edge. Whether you're a business owner, analyst, or student, mastering data visualization will help you see the bigger picture - literally.",
    coverImage: "https://www.instinctools.com/wp-content/uploads/2022/12/data-visualization-preview.jpg",
    author: "68152920f5b0da7c4cd7837c",
    tags: ["DataVisualization", "PowerBI", "Dashboards"],
    category: "Technology",
    isPublished: false,
    readingTime: "2 min",
    views: 8,
    createdAt: new Date("2025-05-02T20:41:16.838Z"),
    updatedAt: new Date("2025-05-27T06:59:00.000Z")
  },
  {
    title: "The Journey into Web Development: From Basics to Brilliance",
    slug: "the-journey-into-web-development-from-basics-to-brilliance",
    content: "Introduction\nWeb development is the heartbeat of the modern internet. Every website, application, or service you use—from social media platforms to online shopping—relies on a well-structured web foundation. But how does it all work? And where do you begin if you're new to it?\n\nIn this blog, I’ll walk you through the basics of web development, how to get started, key tools and technologies, and why it’s such an exciting field for aspiring developers like us.\n\nWhat is Web Development?\nWeb development is the process of building and maintaining websites. It involves everything from creating static pages to complex web applications. There are three core types of web development:\nFrontend Development – The part of the website you see and interact with.\nBackend Development – The server-side logic that handles data processing, authentication, and APIs.\nFull Stack Development – A combination of both frontend and backend.\n\n💡 Key Technologies\n🔹 Frontend:\nHTML – Structure of the page.\n\nCSS / Tailwind CSS – Styling and design.\n\nJavaScript – Interactivity and dynamic behavior.\n\nReact / Next.js – Modern frontend frameworks for building scalable apps.\n\n🔹 Backend:\nNode.js & Express.js – Run JavaScript on the server.\n\nMongoDB / MySQL – Databases to store user data.\n\nAPIs – Bridge between frontend and backend.\n\n🔹 Tools:\nGit & GitHub – Version control and collaboration.\n\nVercel / Netlify – Free and easy deployment platforms.\n\nVS Code – The most popular code editor for web development.\n\n🛠️ My Web Dev Projects\nI’ve worked on several projects that helped me grow as a developer. One such project is:\n\n🔸 ChatME-Ai – A real-time AI chatbot built using Next.js, integrating Gemini API for smart responses. It features clean UI, real-time message handling, and shows how powerful serverless frontend applications can be.\n\n🔗 View Project\n\n🚀 Why Web Development is Amazing\nYou instantly see results in the browser.\n\nYou can build anything from personal blogs to e-commerce sites.\n\nIt fosters both creativity and logic.\n\nThere's a huge community and endless resources to learn from.\n\n📚 Tips for Beginners\nStart with HTML, CSS, and JavaScript.\n\nBuild small projects: portfolio sites, to-do lists, calculators.\n\nLearn Git early on.\n\nUse free platforms like GitHub, Vercel, and Netlify for deployment.\n\nJoin communities like Stack Overflow, Discord servers, or Reddit.",
    coverImage: "https://miro.medium.com/v2/resize:fit:1200/1*V-Jp13LvtVc2IiY2fp4qYw.jpeg",
    author: "681f6b84614b452e35fc9e29",
    tags: ["web dev", "Full Stack Development"],
    category: "Technology",
    isPublished: false,
    readingTime: "2 min",
    views: 6,
    createdAt: new Date("2025-05-26T18:46:38.563Z"),
    updatedAt: new Date("2025-05-27T06:59:00.000Z")
  },
  {
    title: "Exploring Machine Learning for Beginners",
    slug: "exploring-machine-learning-beginners",
    content: "Introduction\nMachine learning (ML) is a transformative technology that powers everything from recommendation systems to autonomous vehicles. This blog is a beginner’s guide to understanding ML, its key algorithms, and how to start your journey.\n\nWhat is Machine Learning?\nMachine learning is a subset of AI that enables computers to learn from data without explicit programming. It’s about finding patterns and making predictions based on data.\n\nKey Algorithms:\n- Linear Regression: Predicts numerical values.\n- Logistic Regression: Classifies data into categories.\n- Decision Trees: Makes decisions based on feature hierarchies.\n- Neural Networks: Mimics human brain for complex tasks like image recognition.\n\nGetting Started:\n- Learn Python and libraries like Scikit-learn, TensorFlow, or PyTorch.\n- Start with simple datasets (e.g., Iris or Titanic from Kaggle).\n- Explore free courses on Coursera or fast.ai.\n\nPractical Applications:\n- Healthcare: Predicting disease outbreaks.\n- Finance: Fraud detection.\n- Retail: Customer behavior analysis.\n\nFinal Thoughts:\nMachine learning is an exciting field with endless possibilities. Start with small projects, experiment with datasets, and join communities like Kaggle to grow your skills.",
    coverImage: "https://images.unsplash.com/photo-1516321310762-9d8e315a7e84?q=80&w=2000&auto=format&fit=crop",
    author: "68152920f5b0da7c4cd7837c",
    tags: ["Machine Learning", "AI", "Python"],
    category: "Technology",
    isPublished: true,
    readingTime: "3 min",
    views: 10,
    createdAt: new Date("2025-05-27T06:59:00.000Z"),
    updatedAt: new Date("2025-05-27T06:59:00.000Z")
  },
  {
    title: "Sustainable Travel: Tips for Eco-Conscious Adventures",
    slug: "sustainable-travel-eco-conscious",
    content: "Introduction\nTraveling can be both exciting and environmentally responsible. This blog shares tips for sustainable travel, helping you explore the world while minimizing your carbon footprint.\n\nWhy Sustainable Travel?\nWith climate change concerns, travelers are seeking ways to reduce their impact. Sustainable travel preserves destinations for future generations.\n\nTips for Eco-Conscious Travel:\n- Choose eco-friendly accommodations like green hotels or homestays.\n- Use public transport or bike rentals instead of cars.\n- Support local businesses to boost the economy.\n- Pack light to reduce fuel consumption.\n\nDestinations to Explore:\n- Costa Rica: Known for eco-tourism and biodiversity.\n- Norway: Offers sustainable fjord cruises.\n- Bhutan: Prioritizes low-impact tourism.\n\nFinal Thoughts:\nSustainable travel is about making mindful choices. Start small, and your adventures can contribute to a healthier planet.",
    coverImage: "https://images.unsplash.com/photo-1507525428034-b723cf961d3e?q=80&w=2000&auto=format&fit=crop",
    author: "6811dcf7d835fa34c6201ca8",
    tags: ["Travel", "Sustainability", "Eco"],
    category: "Travel",
    isPublished: true,
    readingTime: "3 min",
    views: 15,
    createdAt: new Date("2025-05-27T06:59:00.000Z"),
    updatedAt: new Date("2025-05-27T06:59:00.000Z")
  }
];

module.exports = blogs;